<?php
echo '<!DOCTYPE html>';
echo '<html lang="fr">';
echo '<head>';
echo '    <meta charset="UTF-8">';
echo '    <meta name="viewport" content="width=device-width, initial-scale=1.0">';
echo '    <title>Galaxie Dynamique</title>';
echo '    <style>';
echo '        body { margin: 0; padding: 0; overflow: hidden; background: #000; }';
echo '        canvas { width: 100vw; height: 100vh; display: block; }';
echo '    </style>';
echo '</head>';
echo '<body>';
echo '    <canvas id="galaxyCanvas"></canvas>';
echo '    <audio id="ambientSound" loop src="data:audio/mp3;base64,...(base64 ambient space sound)..."></audio>';
echo '    <audio id="pulseSound" src="data:audio/wav;base64,...(base64 pulse sound)..."></audio>';
echo '    <script>';
echo '        const canvas = document.getElementById("galaxyCanvas");';
echo '        const ctx = canvas.getContext("2d");';
echo '        canvas.width = window.innerWidth;';
echo '        canvas.height = window.innerHeight;';
echo '        let particles = [];';
echo '        let mouse = { x: canvas.width / 2, y: canvas.height / 2 };';
echo '        const ambientSound = document.getElementById("ambientSound");';
echo '        const pulseSound = document.getElementById("pulseSound");';
echo '        let time = 0;';
echo '';
echo '        // Écouteurs d\'événements';
echo '        canvas.addEventListener("mousemove", (e) => {';
echo '            mouse.x = e.offsetX;';
echo '            mouse.y = e.offsetY;';
echo '        });';
echo '        canvas.addEventListener("click", () => {';
echo '            createNebula(mouse.x, mouse.y);';
echo '            pulseSound.play();';
echo '        });';
echo '        window.addEventListener("resize", () => {';
echo '            canvas.width = window.innerWidth;';
echo '            canvas.height = window.innerHeight;';
echo '        });';
echo '';
echo '        // Création des particules (étoiles, poussière, etc.)';
echo '        function createParticle(x, y, type = "star") {';
echo '            return {';
echo '                x, y,';
echo '                vx: (Math.random() - 0.5) * 2,';
echo '                vy: (Math.random() - 0.5) * 2,';
echo '                size: type === "star" ? Math.random() * 2 + 1 : Math.random() * 5 + 2,';
echo '                color: type === "star" ? `hsl(${Math.random() * 360}, 100%, 80%)` : `hsla(${Math.random() * 360}, 70%, 50%, 0.5)`,';
echo '                life: type === "star" ? Infinity : Math.random() * 100 + 50,';
echo '                type,';
echo '                angle: Math.random() * Math.PI * 2';
echo '            };';
echo '        }';
echo '';
echo '        // Création d\'une nébuleuse';
echo '        function createNebula(x, y) {';
echo '            for (let i = 0; i < 50; i++) {';
echo '                particles.push(createParticle(x + (Math.random() - 0.5) * 100, y + (Math.random() - 0.5) * 100, "nebula"));';
echo '            }';
echo '        }';
echo '';
echo '        // Initialisation des étoiles';
echo '        for (let i = 0; i < 500; i++) {';
echo '            particles.push(createParticle(Math.random() * canvas.width, Math.random() * canvas.height));';
echo '        }';
echo '';
echo '        // Dessin du fond et effets de lumière';
echo '        function drawBackground() {';
echo '            ctx.fillStyle = "#000";';
echo '            ctx.fillRect(0, 0, canvas.width, canvas.height);';
echo '            ctx.fillStyle = "rgba(10, 20, 50, 0.1)";';
echo '            ctx.beginPath();';
echo '            ctx.arc(canvas.width / 2, canvas.height / 2, Math.max(canvas.width, canvas.height) * 0.4, 0, Math.PI * 2);';
echo '            ctx.fill();';
echo '        }';
echo '';
echo '        // Dessin des particules avec effets dynamiques';
echo '        function drawParticles() {';
echo '            particles.forEach((p, i) => {';
echo '                if (p.type === "star") {';
echo '                    p.x += Math.cos(p.angle) * 0.1;';
echo '                    p.y += Math.sin(p.angle) * 0.1;';
echo '                } else {';
echo '                    p.x += p.vx;';
echo '                    p.y += p.vy;';
echo '                    p.life -= 1;';
echo '                }';
echo '';
echo '                // Gravité vers la souris';
echo '                let dx = mouse.x - p.x;';
echo '                let dy = mouse.y - p.y;';
echo '                let dist = Math.sqrt(dx * dx + dy * dy);';
echo '                if (dist < 200) {';
echo '                    p.vx += dx / dist * 0.05;';
echo '                    p.vy += dy / dist * 0.05;';
echo '                }';
echo '';
echo '                if (p.life <= 0) {';
echo '                    particles.splice(i, 1);';
echo '                    return;';
echo '                }';
echo '';
echo '                ctx.fillStyle = p.color;';
echo '                ctx.beginPath();';
echo '                ctx.arc(p.x, p.y, p.size, 0, Math.PI * 2);';
echo '                ctx.fill();';
echo '';
echo '                // Effet de lueur';
echo '                ctx.shadowBlur = p.type === "star" ? 10 : 20;';
echo '                ctx.shadowColor = p.color;';
echo '            });';
echo '        }';
echo '';
echo '        // Spirale galactique';
echo '        function drawGalaxySpiral() {';
echo '            ctx.strokeStyle = "rgba(255, 255, 255, 0.1)";';
echo '            ctx.lineWidth = 2;';
echo '            for (let i = 0; i < 4; i++) {';
echo '                ctx.beginPath();';
echo '                for (let t = 0; t < Math.PI * 4; t += 0.1) {';
echo '                    let r = t * 50;';
echo '                    let x = canvas.width / 2 + r * Math.cos(t + time * 0.1 + i * Math.PI / 2);';
echo '                    let y = canvas.height / 2 + r * Math.sin(t + time * 0.1 + i * Math.PI / 2);';
echo '                    ctx.lineTo(x, y);';
echo '                }';
echo '                ctx.stroke();';
echo '            }';
echo '        }';
echo '';
echo '        // Animation principale';
echo '        function animate() {';
echo '            time += 0.02;';
echo '            drawBackground();';
echo '            drawGalaxySpiral();';
echo '            drawParticles();';
echo '';
echo '            // Ajout aléatoire de particules';
echo '            if (Math.random() > 0.98) {';
echo '                particles.push(createParticle(Math.random() * canvas.width, Math.random() * canvas.height));';
echo '            }';
echo '';
echo '            requestAnimationFrame(animate);';
echo '        }';
echo '';
echo '        // Démarrage';
echo '        ambientSound.play();';
echo '        animate();';
echo '    </script>';
echo '</body>';
echo '</html>';
?>